#############################################################################
# Makefile for building: PowerMonitor
# Generated by qmake (3.1) (Qt 6.4.0)
# Project:  ../PowerMonitor/PowerMonitor.pro
# Template: app
# Command: /home/udrc/qt6.4.0-host/bin/qmake -o Makefile ../PowerMonitor/PowerMonitor.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I../PowerMonitor -I. -I../PowerMonitor/include -I../../qt6.4.0-host/include/QtWidgets -I../../qt6.4.0-host/include/QtGui -I../../qt6.4.0-host/include/QtCore -I. -I../../qt6.4.0-host/mkspecs/linux-clang
QMAKE         = /home/udrc/qt6.4.0-host/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/udrc/qt6.4.0-host/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/udrc/qt6.4.0-host/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PowerMonitor1.0.0
DISTDIR = /home/udrc/powmon/build-PowerMonitor-Desktop-Debug/.tmp/PowerMonitor1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/home/udrc/qt6.4.0-host/lib -Wl,-rpath-link,/home/udrc/qt6.4.0-host/lib
LIBS          = $(SUBLIBS) -L/home/udrc/powmon/PowerMonitor/lib/ -lchartdir /home/udrc/qt6.4.0-host/lib/libQt6Widgets.so /home/udrc/qt6.4.0-host/lib/libQt6Gui.so /home/udrc/qt6.4.0-host/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../PowerMonitor/freqscale_sysfs.cpp \
		../PowerMonitor/main.cpp \
		../PowerMonitor/powmon_sysfs.cpp \
		../PowerMonitor/qchartviewer.cpp \
		../PowerMonitor/realtimemultichart.cpp \
		../PowerMonitor/scale_pmbus_ps.cpp qrc_qmake_qmake_qm_files.cpp \
		moc_qchartviewer.cpp \
		moc_realtimemultichart.cpp
OBJECTS       = freqscale_sysfs.o \
		main.o \
		powmon_sysfs.o \
		qchartviewer.o \
		realtimemultichart.o \
		scale_pmbus_ps.o \
		qrc_qmake_qmake_qm_files.o \
		moc_qchartviewer.o \
		moc_realtimemultichart.o
DIST          = ../../qt6.4.0-host/mkspecs/features/spec_pre.prf \
		../../qt6.4.0-host/mkspecs/common/unix.conf \
		../../qt6.4.0-host/mkspecs/common/linux.conf \
		../../qt6.4.0-host/mkspecs/common/sanitize.conf \
		../../qt6.4.0-host/mkspecs/common/gcc-base.conf \
		../../qt6.4.0-host/mkspecs/common/gcc-base-unix.conf \
		../../qt6.4.0-host/mkspecs/common/clang.conf \
		../../qt6.4.0-host/mkspecs/qconfig.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_charts.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_coap.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_coap_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designer.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_gui.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_help.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_help_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_network.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_network_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sql.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svg.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_tools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webview.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt6.4.0-host/mkspecs/features/qt_functions.prf \
		../../qt6.4.0-host/mkspecs/features/qt_config.prf \
		../../qt6.4.0-host/mkspecs/linux-clang/qmake.conf \
		../../qt6.4.0-host/mkspecs/features/spec_post.prf \
		../PowerMonitor/.qmake.stash \
		../../qt6.4.0-host/mkspecs/features/exclusive_builds.prf \
		../../qt6.4.0-host/mkspecs/features/toolchain.prf \
		../../qt6.4.0-host/mkspecs/features/default_pre.prf \
		../../qt6.4.0-host/mkspecs/features/resolve_config.prf \
		../../qt6.4.0-host/mkspecs/features/default_post.prf \
		../../qt6.4.0-host/mkspecs/features/lrelease.prf \
		../../qt6.4.0-host/mkspecs/features/qml_debug.prf \
		../../qt6.4.0-host/mkspecs/features/warn_on.prf \
		../../qt6.4.0-host/mkspecs/features/qt.prf \
		../../qt6.4.0-host/mkspecs/features/resources_functions.prf \
		../../qt6.4.0-host/mkspecs/features/resources.prf \
		../../qt6.4.0-host/mkspecs/features/moc.prf \
		../../qt6.4.0-host/mkspecs/features/unix/opengl.prf \
		../../qt6.4.0-host/mkspecs/features/uic.prf \
		../../qt6.4.0-host/mkspecs/features/unix/thread.prf \
		../../qt6.4.0-host/mkspecs/features/qmake_use.prf \
		../../qt6.4.0-host/mkspecs/features/file_copies.prf \
		../../qt6.4.0-host/mkspecs/features/testcase_targets.prf \
		../../qt6.4.0-host/mkspecs/features/exceptions.prf \
		../../qt6.4.0-host/mkspecs/features/yacc.prf \
		../../qt6.4.0-host/mkspecs/features/lex.prf \
		../PowerMonitor/PowerMonitor.pro ../PowerMonitor/common.h \
		../PowerMonitor/freqscale_sysfs.h \
		../PowerMonitor/i2c-dev.h \
		../PowerMonitor/pmbus.h \
		../PowerMonitor/powmon_sysfs.h \
		../PowerMonitor/qchartviewer.h \
		../PowerMonitor/realtimemultichart.h \
		../PowerMonitor/scale_pmbus_ps.h ../PowerMonitor/freqscale_sysfs.cpp \
		../PowerMonitor/main.cpp \
		../PowerMonitor/powmon_sysfs.cpp \
		../PowerMonitor/qchartviewer.cpp \
		../PowerMonitor/realtimemultichart.cpp \
		../PowerMonitor/scale_pmbus_ps.cpp
QMAKE_TARGET  = PowerMonitor
DESTDIR       = 
TARGET        = PowerMonitor


first: all
####### Build rules

PowerMonitor:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../PowerMonitor/PowerMonitor.pro ../../qt6.4.0-host/mkspecs/linux-clang/qmake.conf ../../qt6.4.0-host/mkspecs/features/spec_pre.prf \
		../../qt6.4.0-host/mkspecs/common/unix.conf \
		../../qt6.4.0-host/mkspecs/common/linux.conf \
		../../qt6.4.0-host/mkspecs/common/sanitize.conf \
		../../qt6.4.0-host/mkspecs/common/gcc-base.conf \
		../../qt6.4.0-host/mkspecs/common/gcc-base-unix.conf \
		../../qt6.4.0-host/mkspecs/common/clang.conf \
		../../qt6.4.0-host/mkspecs/qconfig.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_charts.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_coap.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_coap_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_core_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designer.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_gui.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_help.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_help_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_network.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_network_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sql.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svg.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_tools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webview.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xml.pri \
		../../qt6.4.0-host/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt6.4.0-host/mkspecs/features/qt_functions.prf \
		../../qt6.4.0-host/mkspecs/features/qt_config.prf \
		../../qt6.4.0-host/mkspecs/linux-clang/qmake.conf \
		../../qt6.4.0-host/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt6.4.0-host/mkspecs/features/exclusive_builds.prf \
		../../qt6.4.0-host/mkspecs/features/toolchain.prf \
		../../qt6.4.0-host/mkspecs/features/default_pre.prf \
		../../qt6.4.0-host/mkspecs/features/resolve_config.prf \
		../../qt6.4.0-host/mkspecs/features/default_post.prf \
		../../qt6.4.0-host/mkspecs/features/lrelease.prf \
		../../qt6.4.0-host/mkspecs/features/qml_debug.prf \
		../../qt6.4.0-host/mkspecs/features/warn_on.prf \
		../../qt6.4.0-host/mkspecs/features/qt.prf \
		../../qt6.4.0-host/mkspecs/features/resources_functions.prf \
		../../qt6.4.0-host/mkspecs/features/resources.prf \
		../../qt6.4.0-host/mkspecs/features/moc.prf \
		../../qt6.4.0-host/mkspecs/features/unix/opengl.prf \
		../../qt6.4.0-host/mkspecs/features/uic.prf \
		../../qt6.4.0-host/mkspecs/features/unix/thread.prf \
		../../qt6.4.0-host/mkspecs/features/qmake_use.prf \
		../../qt6.4.0-host/mkspecs/features/file_copies.prf \
		../../qt6.4.0-host/mkspecs/features/testcase_targets.prf \
		../../qt6.4.0-host/mkspecs/features/exceptions.prf \
		../../qt6.4.0-host/mkspecs/features/yacc.prf \
		../../qt6.4.0-host/mkspecs/features/lex.prf \
		../PowerMonitor/PowerMonitor.pro \
		qmake_qmake_qm_files.qrc \
		../../qt6.4.0-host/lib/libQt6Widgets.prl \
		../../qt6.4.0-host/lib/libQt6Gui.prl \
		../../qt6.4.0-host/lib/libQt6Core.prl
	$(QMAKE) -o Makefile ../PowerMonitor/PowerMonitor.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
../../qt6.4.0-host/mkspecs/features/spec_pre.prf:
../../qt6.4.0-host/mkspecs/common/unix.conf:
../../qt6.4.0-host/mkspecs/common/linux.conf:
../../qt6.4.0-host/mkspecs/common/sanitize.conf:
../../qt6.4.0-host/mkspecs/common/gcc-base.conf:
../../qt6.4.0-host/mkspecs/common/gcc-base-unix.conf:
../../qt6.4.0-host/mkspecs/common/clang.conf:
../../qt6.4.0-host/mkspecs/qconfig.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3danimation_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dcore_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dextras_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dinput_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_3drender_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_charts.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_charts_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_coap.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_coap_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_core.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_core5compat_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_core_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_designer.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_designer_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_gui.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_gui_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_help.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_help_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_httpserver_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_input_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_kms_support_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labssettings_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_languageserver_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_linguist_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_mqtt_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_network.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_network_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_networkauth_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_opcua_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmldom_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3d_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_repparser_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_scxml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_shadertools_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sql.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_sql_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachine_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_svg.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_svg_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_tools_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_uiplugin.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webview.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webview_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_xml.pri:
../../qt6.4.0-host/mkspecs/modules/qt_lib_xml_private.pri:
../../qt6.4.0-host/mkspecs/features/qt_functions.prf:
../../qt6.4.0-host/mkspecs/features/qt_config.prf:
../../qt6.4.0-host/mkspecs/linux-clang/qmake.conf:
../../qt6.4.0-host/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt6.4.0-host/mkspecs/features/exclusive_builds.prf:
../../qt6.4.0-host/mkspecs/features/toolchain.prf:
../../qt6.4.0-host/mkspecs/features/default_pre.prf:
../../qt6.4.0-host/mkspecs/features/resolve_config.prf:
../../qt6.4.0-host/mkspecs/features/default_post.prf:
../../qt6.4.0-host/mkspecs/features/lrelease.prf:
../../qt6.4.0-host/mkspecs/features/qml_debug.prf:
../../qt6.4.0-host/mkspecs/features/warn_on.prf:
../../qt6.4.0-host/mkspecs/features/qt.prf:
../../qt6.4.0-host/mkspecs/features/resources_functions.prf:
../../qt6.4.0-host/mkspecs/features/resources.prf:
../../qt6.4.0-host/mkspecs/features/moc.prf:
../../qt6.4.0-host/mkspecs/features/unix/opengl.prf:
../../qt6.4.0-host/mkspecs/features/uic.prf:
../../qt6.4.0-host/mkspecs/features/unix/thread.prf:
../../qt6.4.0-host/mkspecs/features/qmake_use.prf:
../../qt6.4.0-host/mkspecs/features/file_copies.prf:
../../qt6.4.0-host/mkspecs/features/testcase_targets.prf:
../../qt6.4.0-host/mkspecs/features/exceptions.prf:
../../qt6.4.0-host/mkspecs/features/yacc.prf:
../../qt6.4.0-host/mkspecs/features/lex.prf:
../PowerMonitor/PowerMonitor.pro:
qmake_qmake_qm_files.qrc:
../../qt6.4.0-host/lib/libQt6Widgets.prl:
../../qt6.4.0-host/lib/libQt6Gui.prl:
../../qt6.4.0-host/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../PowerMonitor/PowerMonitor.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile PowerMonitor

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../PowerMonitor/PowerMonitor_en_GB.ts $(DISTDIR)/
	$(COPY_FILE) --parents qmake_qmake_qm_files.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../qt6.4.0-host/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../PowerMonitor/common.h ../PowerMonitor/freqscale_sysfs.h ../PowerMonitor/i2c-dev.h ../PowerMonitor/pmbus.h ../PowerMonitor/powmon_sysfs.h ../PowerMonitor/qchartviewer.h ../PowerMonitor/realtimemultichart.h ../PowerMonitor/scale_pmbus_ps.h $(DISTDIR)/
	$(COPY_FILE) --parents ../PowerMonitor/freqscale_sysfs.cpp ../PowerMonitor/main.cpp ../PowerMonitor/powmon_sysfs.cpp ../PowerMonitor/qchartviewer.cpp ../PowerMonitor/realtimemultichart.cpp ../PowerMonitor/scale_pmbus_ps.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../PowerMonitor/PowerMonitor_en_GB.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_lrelease_make_all: .qm/PowerMonitor_en_GB.qm
compiler_lrelease_clean:
	-$(DEL_FILE) .qm/PowerMonitor_en_GB.qm
.qm/PowerMonitor_en_GB.qm: ../PowerMonitor/PowerMonitor_en_GB.ts
	/home/udrc/qt6.4.0-host/bin/lrelease ../PowerMonitor/PowerMonitor_en_GB.ts -qm .qm/PowerMonitor_en_GB.qm

compiler_rcc_make_all: qrc_qmake_qmake_qm_files.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qmake_qmake_qm_files.cpp
qrc_qmake_qmake_qm_files.cpp: qmake_qmake_qm_files.qrc \
		../../qt6.4.0-host/libexec/rcc \
		.qm/PowerMonitor_en_GB.qm
	/home/udrc/qt6.4.0-host/libexec/rcc -name qmake_qmake_qm_files --no-zstd qmake_qmake_qm_files.qrc -o qrc_qmake_qmake_qm_files.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../qt6.4.0-host/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h ../../qt6.4.0-host/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qchartviewer.cpp moc_realtimemultichart.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qchartviewer.cpp moc_realtimemultichart.cpp
moc_qchartviewer.cpp: ../PowerMonitor/qchartviewer.h \
		../../qt6.4.0-host/include/QtWidgets/QLabel \
		../../qt6.4.0-host/include/QtWidgets/qlabel.h \
		../../qt6.4.0-host/include/QtCore/QElapsedTimer \
		../../qt6.4.0-host/include/QtCore/qelapsedtimer.h \
		../PowerMonitor/include/chartdir.h \
		../PowerMonitor/include/bchartdir.h \
		../PowerMonitor/include/memblock.h \
		moc_predefs.h \
		../../qt6.4.0-host/libexec/moc
	/home/udrc/qt6.4.0-host/libexec/moc $(DEFINES) --include /home/udrc/powmon/build-PowerMonitor-Desktop-Debug/moc_predefs.h -I/home/udrc/qt6.4.0-host/mkspecs/linux-clang -I/home/udrc/powmon/PowerMonitor -I/home/udrc/powmon/PowerMonitor/include -I/home/udrc/qt6.4.0-host/include/QtWidgets -I/home/udrc/qt6.4.0-host/include/QtGui -I/home/udrc/qt6.4.0-host/include/QtCore -I. -I. -I/home/udrc/qt6.4.0-host/include -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/llvm-14/lib/clang/14.0.0/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ../PowerMonitor/qchartviewer.h -o moc_qchartviewer.cpp

moc_realtimemultichart.cpp: ../PowerMonitor/realtimemultichart.h \
		../../qt6.4.0-host/include/QtWidgets/QDialog \
		../../qt6.4.0-host/include/QtWidgets/qdialog.h \
		../../qt6.4.0-host/include/QtCore/QThread \
		../../qt6.4.0-host/include/QtCore/qthread.h \
		../../qt6.4.0-host/include/QtCore/QMutex \
		../../qt6.4.0-host/include/QtCore/qmutex.h \
		../../qt6.4.0-host/include/QtCore/QDateTime \
		../../qt6.4.0-host/include/QtCore/qdatetime.h \
		../../qt6.4.0-host/include/QtCore/QTimer \
		../../qt6.4.0-host/include/QtCore/qtimer.h \
		../../qt6.4.0-host/include/QtWidgets/QLabel \
		../../qt6.4.0-host/include/QtWidgets/qlabel.h \
		../../qt6.4.0-host/include/QtWidgets/QLineEdit \
		../../qt6.4.0-host/include/QtWidgets/qlineedit.h \
		../../qt6.4.0-host/include/QtWidgets/QScrollBar \
		../../qt6.4.0-host/include/QtWidgets/qscrollbar.h \
		../../qt6.4.0-host/include/QtWidgets/QButtonGroup \
		../../qt6.4.0-host/include/QtWidgets/qbuttongroup.h \
		../../qt6.4.0-host/include/QtWidgets/QComboBox \
		../../qt6.4.0-host/include/QtWidgets/qcombobox.h \
		../../qt6.4.0-host/include/QtWidgets/QDoubleSpinBox \
		../../qt6.4.0-host/include/QtWidgets/qspinbox.h \
		../PowerMonitor/qchartviewer.h \
		../../qt6.4.0-host/include/QtCore/QElapsedTimer \
		../../qt6.4.0-host/include/QtCore/qelapsedtimer.h \
		../PowerMonitor/include/chartdir.h \
		../PowerMonitor/include/bchartdir.h \
		../PowerMonitor/include/memblock.h \
		../PowerMonitor/scale_pmbus_ps.h \
		../PowerMonitor/common.h \
		../PowerMonitor/i2c-dev.h \
		../PowerMonitor/powmon_sysfs.h \
		../PowerMonitor/freqscale_sysfs.h \
		moc_predefs.h \
		../../qt6.4.0-host/libexec/moc
	/home/udrc/qt6.4.0-host/libexec/moc $(DEFINES) --include /home/udrc/powmon/build-PowerMonitor-Desktop-Debug/moc_predefs.h -I/home/udrc/qt6.4.0-host/mkspecs/linux-clang -I/home/udrc/powmon/PowerMonitor -I/home/udrc/powmon/PowerMonitor/include -I/home/udrc/qt6.4.0-host/include/QtWidgets -I/home/udrc/qt6.4.0-host/include/QtGui -I/home/udrc/qt6.4.0-host/include/QtCore -I. -I. -I/home/udrc/qt6.4.0-host/include -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/llvm-14/lib/clang/14.0.0/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ../PowerMonitor/realtimemultichart.h -o moc_realtimemultichart.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_lrelease_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

freqscale_sysfs.o: ../PowerMonitor/freqscale_sysfs.cpp ../PowerMonitor/freqscale_sysfs.h \
		../PowerMonitor/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o freqscale_sysfs.o ../PowerMonitor/freqscale_sysfs.cpp

main.o: ../PowerMonitor/main.cpp ../../qt6.4.0-host/include/QtWidgets/QApplication \
		../../qt6.4.0-host/include/QtWidgets/qapplication.h \
		../../qt6.4.0-host/include/QtCore/QLocale \
		../../qt6.4.0-host/include/QtCore/qlocale.h \
		../../qt6.4.0-host/include/QtCore/QTranslator \
		../../qt6.4.0-host/include/QtCore/qtranslator.h \
		../PowerMonitor/realtimemultichart.h \
		../../qt6.4.0-host/include/QtWidgets/QDialog \
		../../qt6.4.0-host/include/QtWidgets/qdialog.h \
		../../qt6.4.0-host/include/QtCore/QThread \
		../../qt6.4.0-host/include/QtCore/qthread.h \
		../../qt6.4.0-host/include/QtCore/QMutex \
		../../qt6.4.0-host/include/QtCore/qmutex.h \
		../../qt6.4.0-host/include/QtCore/QDateTime \
		../../qt6.4.0-host/include/QtCore/qdatetime.h \
		../../qt6.4.0-host/include/QtCore/QTimer \
		../../qt6.4.0-host/include/QtCore/qtimer.h \
		../../qt6.4.0-host/include/QtWidgets/QLabel \
		../../qt6.4.0-host/include/QtWidgets/qlabel.h \
		../../qt6.4.0-host/include/QtWidgets/QLineEdit \
		../../qt6.4.0-host/include/QtWidgets/qlineedit.h \
		../../qt6.4.0-host/include/QtWidgets/QScrollBar \
		../../qt6.4.0-host/include/QtWidgets/qscrollbar.h \
		../../qt6.4.0-host/include/QtWidgets/QButtonGroup \
		../../qt6.4.0-host/include/QtWidgets/qbuttongroup.h \
		../../qt6.4.0-host/include/QtWidgets/QComboBox \
		../../qt6.4.0-host/include/QtWidgets/qcombobox.h \
		../../qt6.4.0-host/include/QtWidgets/QDoubleSpinBox \
		../../qt6.4.0-host/include/QtWidgets/qspinbox.h \
		../PowerMonitor/qchartviewer.h \
		../../qt6.4.0-host/include/QtCore/QElapsedTimer \
		../../qt6.4.0-host/include/QtCore/qelapsedtimer.h \
		../PowerMonitor/include/chartdir.h \
		../PowerMonitor/include/bchartdir.h \
		../PowerMonitor/include/memblock.h \
		../PowerMonitor/scale_pmbus_ps.h \
		../PowerMonitor/common.h \
		../PowerMonitor/i2c-dev.h \
		../PowerMonitor/powmon_sysfs.h \
		../PowerMonitor/freqscale_sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../PowerMonitor/main.cpp

powmon_sysfs.o: ../PowerMonitor/powmon_sysfs.cpp ../PowerMonitor/powmon_sysfs.h \
		../PowerMonitor/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powmon_sysfs.o ../PowerMonitor/powmon_sysfs.cpp

qchartviewer.o: ../PowerMonitor/qchartviewer.cpp ../PowerMonitor/qchartviewer.h \
		../../qt6.4.0-host/include/QtWidgets/QLabel \
		../../qt6.4.0-host/include/QtWidgets/qlabel.h \
		../../qt6.4.0-host/include/QtCore/QElapsedTimer \
		../../qt6.4.0-host/include/QtCore/qelapsedtimer.h \
		../PowerMonitor/include/chartdir.h \
		../PowerMonitor/include/bchartdir.h \
		../PowerMonitor/include/memblock.h \
		../../qt6.4.0-host/include/QtWidgets/QApplication \
		../../qt6.4.0-host/include/QtWidgets/qapplication.h \
		../../qt6.4.0-host/include/QtGui/QMouseEvent \
		../../qt6.4.0-host/include/QtGui/qevent.h \
		../../qt6.4.0-host/include/QtWidgets/QToolTip \
		../../qt6.4.0-host/include/QtWidgets/qtooltip.h \
		../../qt6.4.0-host/include/QtGui/QCursor \
		../../qt6.4.0-host/include/QtGui/qcursor.h \
		../../qt6.4.0-host/include/QtGui/QBitmap \
		../../qt6.4.0-host/include/QtGui/qbitmap.h \
		../../qt6.4.0-host/include/QtCore/QFile \
		../../qt6.4.0-host/include/QtCore/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qchartviewer.o ../PowerMonitor/qchartviewer.cpp

realtimemultichart.o: ../PowerMonitor/realtimemultichart.cpp ../../qt6.4.0-host/include/QtWidgets/QApplication \
		../../qt6.4.0-host/include/QtWidgets/qapplication.h \
		../../qt6.4.0-host/include/QtGui/QIcon \
		../../qt6.4.0-host/include/QtGui/qicon.h \
		../../qt6.4.0-host/include/QtWidgets/QPushButton \
		../../qt6.4.0-host/include/QtWidgets/qpushbutton.h \
		../../qt6.4.0-host/include/QtWidgets/QFileDialog \
		../../qt6.4.0-host/include/QtWidgets/qfiledialog.h \
		../../qt6.4.0-host/include/QtCore/QProcess \
		../../qt6.4.0-host/include/QtCore/qprocess.h \
		../../qt6.4.0-host/include/QtCore/QDebug \
		../../qt6.4.0-host/include/QtCore/qdebug.h \
		../PowerMonitor/realtimemultichart.h \
		../../qt6.4.0-host/include/QtWidgets/QDialog \
		../../qt6.4.0-host/include/QtWidgets/qdialog.h \
		../../qt6.4.0-host/include/QtCore/QThread \
		../../qt6.4.0-host/include/QtCore/qthread.h \
		../../qt6.4.0-host/include/QtCore/QMutex \
		../../qt6.4.0-host/include/QtCore/qmutex.h \
		../../qt6.4.0-host/include/QtCore/QDateTime \
		../../qt6.4.0-host/include/QtCore/qdatetime.h \
		../../qt6.4.0-host/include/QtCore/QTimer \
		../../qt6.4.0-host/include/QtCore/qtimer.h \
		../../qt6.4.0-host/include/QtWidgets/QLabel \
		../../qt6.4.0-host/include/QtWidgets/qlabel.h \
		../../qt6.4.0-host/include/QtWidgets/QLineEdit \
		../../qt6.4.0-host/include/QtWidgets/qlineedit.h \
		../../qt6.4.0-host/include/QtWidgets/QScrollBar \
		../../qt6.4.0-host/include/QtWidgets/qscrollbar.h \
		../../qt6.4.0-host/include/QtWidgets/QButtonGroup \
		../../qt6.4.0-host/include/QtWidgets/qbuttongroup.h \
		../../qt6.4.0-host/include/QtWidgets/QComboBox \
		../../qt6.4.0-host/include/QtWidgets/qcombobox.h \
		../../qt6.4.0-host/include/QtWidgets/QDoubleSpinBox \
		../../qt6.4.0-host/include/QtWidgets/qspinbox.h \
		../PowerMonitor/qchartviewer.h \
		../../qt6.4.0-host/include/QtCore/QElapsedTimer \
		../../qt6.4.0-host/include/QtCore/qelapsedtimer.h \
		../PowerMonitor/include/chartdir.h \
		../PowerMonitor/include/bchartdir.h \
		../PowerMonitor/include/memblock.h \
		../PowerMonitor/scale_pmbus_ps.h \
		../PowerMonitor/common.h \
		../PowerMonitor/i2c-dev.h \
		../PowerMonitor/powmon_sysfs.h \
		../PowerMonitor/freqscale_sysfs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o realtimemultichart.o ../PowerMonitor/realtimemultichart.cpp

scale_pmbus_ps.o: ../PowerMonitor/scale_pmbus_ps.cpp ../PowerMonitor/scale_pmbus_ps.h \
		../PowerMonitor/common.h \
		../PowerMonitor/i2c-dev.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scale_pmbus_ps.o ../PowerMonitor/scale_pmbus_ps.cpp

qrc_qmake_qmake_qm_files.o: qrc_qmake_qmake_qm_files.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_qmake_qm_files.o qrc_qmake_qmake_qm_files.cpp

moc_qchartviewer.o: moc_qchartviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qchartviewer.o moc_qchartviewer.cpp

moc_realtimemultichart.o: moc_realtimemultichart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_realtimemultichart.o moc_realtimemultichart.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/PowerMonitor/bin || mkdir -p $(INSTALL_ROOT)/opt/PowerMonitor/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/PowerMonitor/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/PowerMonitor/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/PowerMonitor/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

